### ISSUE TITLE
auro-interruption: return user to the trigger element upon modal closure when in a nested shadow root

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-interruption#38]
## Is your feature request related to a problem? Please describe.

It's best practice when closing modals for the focus to be put back on the element the modal was triggered from. Depending on implementation, this can be somewhat tricky. 

## Describe the solution you'd like

A new attribute added onto auro-interruption 'triggerRef' could take either an id or a query selector to return the user to the element that triggered the modal. In some cases like for upsells that are time-launched and not by a trigger by the guest, this feature would be extra helpful.

## Describe alternatives you've considered

There's a lot of ways to implement this in consuming codebases, but this feels like a developer experience improvement we can address from the design system.

**Comment by blackfalcon** [comment]
@gusnaughton when I use the demo at https://auro.alaskaair.com/components/auro/interruption I can do the following. 

1. tab to the trigger
2. open the dialog with the RETURN key
3. I can tab to the X
4. I can close the dialog with the RETURN KEY

Any scenario where I am using keyboard commands to open and close the dialog returns me to the initial trigger. 

Is this NOT the scenario you are seeing?

**Comment by geoffrich** [comment]
We are currently implementing this in auro-interruption by storing `document.activeElement` on open and re-focusing it on close.

https://github.com/AlaskaAirlines/auro-interruption/blob/75f988d2157912a0d2e0d6c08155e986514b0fa8/src/component-base.js#L107-L123

I'm guessing `document.activeElement` does not reference the right element when the focused element is in a nested shadow root -- it seems that in the page you linked, the hyperlink that triggered the modal is at least 3 shadow roots deep.

In this case, I don't think a query selector would work due to the shadow roots -- `document.querySelector('#originalId')` is not going to find the element inside another element's shadow.

Should we expose `triggerElement` as a prop that can be set by the consumer? This should be an actual DOM reference, not a query string. We can fallback to `document.activeElement` if not set.

**Comment by geoffrich** [comment]
Alternatively, looks like shadowRoots have an [active element](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/activeElement). We could recursively traverse shadowRoots until we get to the actually active element.

**Comment by blackfalcon** [comment]
@geoffrich I like the idea of exposing `triggerElement` as a prop to address this and then creating a story for active element as a future enhancement. 

So you are saying that the value of `triggerElement` would be the ID of the trigger element?

**Comment by geoffrich** [comment]
No, we can't use ID in this case. We need the actual DOM element to be passed (i.e. what `querySelector` returns). We won't be able to query for the ID because it's nested in another shadow root.

**Comment by blackfalcon** [comment]
@geoffrich will be addressing this issue in this sprint.

**Comment by geoffrich** [comment]
See the test [nested-shadow element](https://github.com/AlaskaAirlines/auro-interruption/blob/8548b921c00a7b8c9bde87ebffdb79d697ddeb1f/test/nested-shadow.js) as an example of how to set the trigger element. If set, the dialog will return focus to that element. This should only be necessary when the dialog trigger is inside a shadow root.

#40 will improve our automatic detection so this should be unnecessary in most cases.
